# Site settings
title: Bit by Bit
description: Peter Bhabra's blog.
author: Peter Bhabra
url: "https://pjb157.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme
theme: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
